# -*- coding: utf-8 -*-
"""k_NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ncBmZqJmSQS7MiZgLmDtdDBuBcNwisU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns


train_datasets = [
    "datasets/training/training_data_ID_numeric.csv",
    "datasets/training/training_data_ID_numeric_adasyn.csv",
    "datasets/training/training_data_ID_numeric_clusterbased.csv",
    "datasets/training/training_data_ID_numeric_nearmiss.csv",
    "datasets/training/training_data_ID_numeric_smote.csv"
]

# Test ve validation veri setleri
test_data = pd.read_csv("datasets/test/test_data_ID_numeric.csv").drop(columns=['ID'])
validation_data = pd.read_csv("datasets/validation/validation_data_ID_numeric.csv").drop(columns=['ID'])

X_test = test_data.iloc[:, :-1].values #independent var for test
y_test = test_data.iloc[:, -1].values #column label for test

X_val = validation_data.iloc[:, :-1].values #independent var for validation dataset
y_val = validation_data.iloc[:, -1].values

# Her bir eğitim datasetini ayrı ayrı işle
for dataset_path in train_datasets:
    # train sette IDyi dropla, her model için optimal k değeri bul.
    train_data = pd.read_csv(dataset_path).drop(columns=['ID'])

    X_train = train_data.iloc[:, :-1].values  # independent variables
    y_train = train_data.iloc[:, -1].values  # column label

    print(f"\n=== İşlenen Dataset: {dataset_path} ===")

    # Optimal k değerini bul
    k_values = range(1, 31)
    accuracies = []

    #1-31 arası k değerleri kullanılarak model oluşturulur
    #X_val değerleriyle tahmin edilir, y_val değeriyle karşılaştırılır.
    for k in k_values:
        knn = KNeighborsClassifier(n_neighbors=k, metric='euclidean')
        knn.fit(X_train, y_train)
        y_val_pred = knn.predict(X_val)
        accuracy = accuracy_score(y_val, y_val_pred)
        accuracies.append(accuracy)

    # Optimal k değerini seç
    optimal_k = np.argmax(accuracies) + 1
    print(f"Optimal k (validation set): {optimal_k}")

    # Validasyon doğruluklarını görselleştir
    plt.figure(figsize=(10, 6))
    plt.plot(k_values, accuracies, marker='o', linestyle='-', color='b')
    plt.axvline(optimal_k, color='r', linestyle='--', label=f'Optimal k = {optimal_k}')
    plt.title(f'Validation Accuracy vs. k (Dataset: {dataset_path})')
    plt.xlabel('k Value')
    plt.ylabel('Validation Accuracy')
    plt.legend()
    plt.grid(True)
    plt.show()

    # Optimal k ile validation ve test setlerinde doğruluk oranlarını hesapla
    final_knn = KNeighborsClassifier(n_neighbors=optimal_k, metric='euclidean')
    final_knn.fit(X_train, y_train)

    # Validation doğruluğu
    y_val_pred = final_knn.predict(X_val)
    val_accuracy = accuracy_score(y_val, y_val_pred)
    print(f"Validation Set Accuracy: {val_accuracy:.4f}")

    # Test doğruluğu
    y_test_pred = final_knn.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    print(f"Test Set Accuracy: {test_accuracy:.4f}")

    # Test sonuçlarını değerlendir
    conf_matrix_test = confusion_matrix(y_test, y_test_pred)
    plt.figure(figsize=(10, 8))  # Heatmap boyutunu ayarlama
    sns.heatmap(conf_matrix_test, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
    plt.title(f'Confusion Matrix (Test Set, Optimal k={optimal_k})')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()
    print("\nClassification Report (Test Set):\n", classification_report(y_test, y_test_pred))

    # Validation sonuçlarını değerlendir
    conf_matrix_val = confusion_matrix(y_val, y_val_pred)
    plt.figure(figsize=(10, 8))  # Heatmap boyutunu ayarlama
    sns.heatmap(conf_matrix_test, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
    plt.title(f'Confusion Matrix (Validation Set, Optimal k={optimal_k})')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()
    print("\nClassification Report (Validation Set):\n", classification_report(y_val, y_val_pred))